# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Zynq-Design-using-Vivado/labsolutions/embedded/2022_2_ebaz4205_labsolution/lab_3/lab_3.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_3/design_1_auto_pc_3.xci
# IP: The module: 'design_1_auto_pc_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Zynq-Design-using-Vivado/labsolutions/embedded/2022_2_ebaz4205_labsolution/lab_3/lab_3.gen/sources_1/bd/design_1/ip/design_1_auto_pc_3/design_1_auto_pc_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_auto_pc_3'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/Zynq-Design-using-Vivado/labsolutions/embedded/2022_2_ebaz4205_labsolution/lab_3/lab_3.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_3/design_1_auto_pc_3.xci
# IP: The module: 'design_1_auto_pc_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Zynq-Design-using-Vivado/labsolutions/embedded/2022_2_ebaz4205_labsolution/lab_3/lab_3.gen/sources_1/bd/design_1/ip/design_1_auto_pc_3/design_1_auto_pc_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_auto_pc_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
