# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/test.xdc

# Block Designs: bd/ebaz_design/ebaz_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz_design || ORIG_REF_NAME==ebaz_design} -quiet] -quiet

# IP: bd/ebaz_design/ip/ebaz_design_processing_system7_0_0/ebaz_design_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz_design_processing_system7_0_0 || ORIG_REF_NAME==ebaz_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/ebaz_design/ip/ebaz_design_axi_gpio_0_0/ebaz_design_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz_design_axi_gpio_0_0 || ORIG_REF_NAME==ebaz_design_axi_gpio_0_0} -quiet] -quiet

# IP: bd/ebaz_design/ip/ebaz_design_auto_pc_0/ebaz_design_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz_design_auto_pc_0 || ORIG_REF_NAME==ebaz_design_auto_pc_0} -quiet] -quiet

# IP: bd/ebaz_design/ip/ebaz_design_ps7_0_axi_periph_0/ebaz_design_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz_design_ps7_0_axi_periph_0 || ORIG_REF_NAME==ebaz_design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/ebaz_design/ip/ebaz_design_rst_ps7_0_50M_0/ebaz_design_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ebaz_design_rst_ps7_0_50M_0 || ORIG_REF_NAME==ebaz_design_rst_ps7_0_50M_0} -quiet] -quiet

# XDC: d:/Zynq-Design-using-Vivado/labsolutions/embedded/2022_2_ebaz4205_labsolution/test_gpio_ebaz/test_gpio_ebaz.gen/sources_1/bd/ebaz_design/ebaz_design_ooc.xdc
