# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Zynq-Design-using-Vivado/labsolutions/embedded/2022_2_ebaz4205_labsolution/test_gpio_ebaz/test_gpio_ebaz.srcs/sources_1/bd/ebaz_design/ip/ebaz_design_rst_ps7_0_50M_0/ebaz_design_rst_ps7_0_50M_0.xci
# IP: The module: 'ebaz_design_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Zynq-Design-using-Vivado/labsolutions/embedded/2022_2_ebaz4205_labsolution/test_gpio_ebaz/test_gpio_ebaz.gen/sources_1/bd/ebaz_design/ip/ebaz_design_rst_ps7_0_50M_0/ebaz_design_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ebaz_design_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Zynq-Design-using-Vivado/labsolutions/embedded/2022_2_ebaz4205_labsolution/test_gpio_ebaz/test_gpio_ebaz.gen/sources_1/bd/ebaz_design/ip/ebaz_design_rst_ps7_0_50M_0/ebaz_design_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ebaz_design_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Zynq-Design-using-Vivado/labsolutions/embedded/2022_2_ebaz4205_labsolution/test_gpio_ebaz/test_gpio_ebaz.gen/sources_1/bd/ebaz_design/ip/ebaz_design_rst_ps7_0_50M_0/ebaz_design_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ebaz_design_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/Zynq-Design-using-Vivado/labsolutions/embedded/2022_2_ebaz4205_labsolution/test_gpio_ebaz/test_gpio_ebaz.srcs/sources_1/bd/ebaz_design/ip/ebaz_design_rst_ps7_0_50M_0/ebaz_design_rst_ps7_0_50M_0.xci
# IP: The module: 'ebaz_design_rst_ps7_0_50M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Zynq-Design-using-Vivado/labsolutions/embedded/2022_2_ebaz4205_labsolution/test_gpio_ebaz/test_gpio_ebaz.gen/sources_1/bd/ebaz_design/ip/ebaz_design_rst_ps7_0_50M_0/ebaz_design_rst_ps7_0_50M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ebaz_design_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Zynq-Design-using-Vivado/labsolutions/embedded/2022_2_ebaz4205_labsolution/test_gpio_ebaz/test_gpio_ebaz.gen/sources_1/bd/ebaz_design/ip/ebaz_design_rst_ps7_0_50M_0/ebaz_design_rst_ps7_0_50M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ebaz_design_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Zynq-Design-using-Vivado/labsolutions/embedded/2022_2_ebaz4205_labsolution/test_gpio_ebaz/test_gpio_ebaz.gen/sources_1/bd/ebaz_design/ip/ebaz_design_rst_ps7_0_50M_0/ebaz_design_rst_ps7_0_50M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ebaz_design_rst_ps7_0_50M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
